exports.named = {
  ERROR_METRIC : "ERROR_METRIC",
  CLICK_METRIC : "CLICK_METRIC"
};
exports.data = {
  LATENCY_METRIC : "LATENCY_METRIC",
  DISK_METRIC : "DISK_METRIC"
};
exports.MINUTE = 1000 * 60 * 60;
